/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabajo.entornos;

import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.JTextPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author prg
 */
public class Catalogo2 extends javax.swing.JDialog {

    /**
     * Creates new form Catalogo2
     */
    DefaultTableModel modelo;
    ArrayList<Producto> alProductos;
    int altoSizeCarrito;

    public Catalogo2(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        alProductos = new ArrayList<Producto>();
        rellenaTabla();
        initComponents();

        this.setLocationRelativeTo(null);

        this.setVisible(true);

    }

    private void actualizaPanelCarrito() {

        pnCarrito.removeAll();

        for (Producto x : alProductos) {

            //JTextPane etiquetaPrd = new JTextPane();
            String aux = x.toString();
            //aux.replaceAll("\t", "    ");
            //JLabel etiquetaProd = new JLabel(aux);
            JTextField area = new JTextField(aux);
            area.setEditable(false);
            area.setBorder(null);
            
            pnCarrito.add(area);
            int altura = pnCarrito.getHeight();
            altura += 40;
            pnCarrito.setPreferredSize(new Dimension(480,altura));

            //String nombreTruncado = x.getNombre();
            //if (x.getNombre().length() >20)
            //nombreTruncado = x.getNombre().substring(0, 20);
//            JLabel lbNombre = new JLabel(nombreTruncado);
//            JLabel lbUnidades = new JLabel(String.valueOf(x.getUnidades()));
//            double precio = x.getPpu() * x.getUnidades();
//            precio = (double) Math.round(precio * 100d) / 100d;
//            JLabel lbPrecio = new JLabel(String.valueOf(precio));
//
//            pnCarrito.add(lbNombre);
//            pnCarrito.add(lbUnidades);
//            pnCarrito.add(lbPrecio);
        }
        pnCarrito.setVisible(false);
        pnCarrito.setVisible(true);
    }

    private void rellenaTabla() {

        MySQL.conecta("pepe", "pepa");
        Object[][] datos = MySQL.getDatos("select idProducto,nombre,cantidad,"
                + "ppu,categoria  from producto;");
        Object[] cabecera = MySQL.getCabecera();
        MySQL.cierraRs();

        modelo = new DefaultTableModel(datos, cabecera) {
            @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false
                return false;
            }
        };

//        jTabla1.setModel(modelo);
        //jTabla1.getColumnModel().getColumn(4).setCellEditor(new DefaultCellEditor(cbCategorias));
        //jTabla1.getModel().addTableModelListener(eventomodelo);
        //clases = MySQL.getClases(tabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabla1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        pnCarrito = new javax.swing.JPanel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jTabla1.setModel(modelo
        );
        jTabla1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabla1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTabla1);

        jScrollPane2.setPreferredSize(new java.awt.Dimension(400, 200));

        pnCarrito.setLayout(new java.awt.GridLayout(0, 1, 0, -20));
        jScrollPane2.setViewportView(pnCarrito);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                        .addGap(217, 217, 217))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(159, 159, 159))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabla1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabla1MouseClicked
        // TODO add your handling code here:
        
        
        String[] productoAux = new String[jTabla1.getColumnCount()];
        int row = jTabla1.rowAtPoint(evt.getPoint());
        int col = jTabla1.columnAtPoint(evt.getPoint());
        if (row >= 0 && col >= 0) {
            for (int i = 0; i < jTabla1.getColumnCount(); i++) {
                productoAux[i] = jTabla1.getModel().getValueAt(row, i).toString();
            }

            Producto prod = new Producto();
            
            if (alProductos.isEmpty()){
                prod.setId(Integer.parseInt(productoAux[0]));
                prod.setNombre(productoAux[1]);
                prod.setUnidades(1);
                prod.setPpu(Double.parseDouble(productoAux[3]));
                prod.setCategoria(productoAux[4]);
                alProductos.add(prod);
            } else
            for (int i = 0; i < alProductos.size(); i++) {
                if (alProductos.get(i).getNombre().compareToIgnoreCase(productoAux[1]) == 0) {
                    alProductos.get(i).setUnidades(alProductos.get(i).getUnidades()+1);
                    break;
                } else {
                    prod.setId(Integer.parseInt(productoAux[0]));
                    prod.setNombre(productoAux[1]);
                    prod.setUnidades(1);
                    prod.setPpu(Double.parseDouble(productoAux[3]));
                    prod.setCategoria(productoAux[4]);
                    alProductos.add(prod);
                }
            }

            actualizaPanelCarrito();
        }
    }//GEN-LAST:event_jTabla1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Catalogo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Catalogo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Catalogo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Catalogo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Catalogo2 dialog = new Catalogo2(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTabla1;
    private javax.swing.JPanel pnCarrito;
    // End of variables declaration//GEN-END:variables
}
