/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabajo.entornos;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JLabel;

/**
 *
 * @author prg
 */
public class HistorialVenta extends javax.swing.JDialog {

    private Object[][] fechas;
    ArrayList<Integer> años;
    ArrayList<Integer> meses;
    ArrayList<String> tickets;
    String ultimoSeleccionado;

    /**
     * Creates new form HistorialVenta
     */
    public HistorialVenta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        MySQL.conecta("pepe", "pepa");
        fechas = MySQL.getDatos("select fecha from ticket;");
        MySQL.cierraRs();
        años = new ArrayList();

        for (int i = 0; i < fechas.length; i++) {
            for (int j = 0; j < fechas[i].length; j++) {
                if (!años.contains(LocalDate.parse(fechas[i][j].toString()).getYear())) {
                    años.add(LocalDate.parse(fechas[i][j].toString()).getYear());
                }
            }
        }

        initComponents();

        for (int x : años) {
            cbAños.addItem(String.valueOf(x));
        }

        this.setLocationRelativeTo(null);
        this.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        FrameDrag = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        cbAños = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbMeses = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnTicketsGrid = new javax.swing.JPanel();
        cbIds = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        FrameDrag.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        FrameDrag.setForeground(new java.awt.Color(204, 204, 204));
        FrameDrag.setText("  Historial de Ventas");

        jSeparator1.setBackground(new java.awt.Color(204, 204, 204));

        cbAños.setBackground(new java.awt.Color(204, 204, 204));
        cbAños.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbAñosItemStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Año");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Mes");

        cbMeses.setBackground(new java.awt.Color(204, 204, 204));
        cbMeses.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbMesesItemStateChanged(evt);
            }
        });
        cbMeses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMesesActionPerformed(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(203, 334));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(203, 334));

        pnTicketsGrid.setBackground(new java.awt.Color(153, 153, 153));
        pnTicketsGrid.setPreferredSize(new java.awt.Dimension(200, 300));
        jScrollPane1.setViewportView(pnTicketsGrid);

        cbIds.setBackground(new java.awt.Color(204, 204, 204));
        cbIds.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbIdsItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(FrameDrag, javax.swing.GroupLayout.PREFERRED_SIZE, 862, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 36, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(cbAños, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(141, 141, 141)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(cbMeses, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbIds, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(FrameDrag, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cbAños)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cbMeses)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbIds, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbAñosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbAñosItemStateChanged
        // TODO add your handling code here:
        Object[][] aux = MySQL.getDatos("select fecha from ticket where fecha like '" + cbAños.getSelectedItem().toString() + "%';");
        MySQL.cierraRs();
        meses = new ArrayList<Integer>();

        for (int i = 0; i < aux.length; i++) {
            for (int j = 0; j < aux[i].length; j++) {
                if (!meses.contains(LocalDate.parse(aux[i][j].toString()).getMonthValue())) {
                    meses.add(LocalDate.parse(aux[i][j].toString()).getMonthValue());
                }
            }
        }
        cbMeses.removeAllItems();
        for (int x : meses) {
            cbMeses.addItem(String.valueOf(x));
        }


    }//GEN-LAST:event_cbAñosItemStateChanged

    private void cbMesesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbMesesItemStateChanged
        // TODO add your handling code here:
        tickets = new ArrayList<String>();
        String ult = "";
        try {
            int ultimo = Integer.parseInt(cbMeses.getSelectedItem().toString());
            if (ultimo < 10) {
                ult = "0" + ultimo;
            } else {
                ult = "" + ultimo;
            }
            Object[][] aux = MySQL.getDatos("select fecha from ticket where fecha like '" + cbAños.getSelectedItem().toString() + "-" + ult + "-%';");
            System.out.println("select fecha from ticket where fecha like '" + cbAños.getSelectedItem().toString() + "-" + ult + "-%';");
            MySQL.cierraRs();
            for (int i = 0; i < aux.length; i++) {
                for (int j = 0; j < aux[i].length; j++) {
                    if (!tickets.contains(aux[i][j].toString())) {
                        tickets.add(aux[i][j].toString());
                    }
                }
            }

            pnTicketsGrid.removeAll();
            int altura = pnTicketsGrid.getHeight();
            for (int i = 0; i < tickets.size(); i++) {
                JLabel etiqueta = new JLabel(tickets.get(i).toString());
                etiqueta.setPreferredSize(new Dimension(180, 30));
                etiqueta.setFont(new java.awt.Font("Helvetica Neue", 0, 14));
                etiqueta.setForeground(Color.white);
                etiqueta.addMouseListener(new MouseAdapter() {
                    public void mouseClicked(MouseEvent e) {

                        Object[][] ticketsAux = MySQL.getDatos("select idTicket from ticket where fecha = '" + etiqueta.getText() + "';");
                        llenaIds(ticketsAux);

                    }
                });
                pnTicketsGrid.add(etiqueta);
                if (i > 9) {
                    System.out.println("pnTicketsGrid.getHeight" + pnTicketsGrid.getHeight());
                    System.out.println("i = " + i);
                    altura += 40;
                    pnTicketsGrid.setPreferredSize(new Dimension(200, altura));

                }
            }
            pnTicketsGrid.setVisible(false);
            pnTicketsGrid.setVisible(true);

        } catch (Exception e) {

        }
    }//GEN-LAST:event_cbMesesItemStateChanged

    private void cbMesesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMesesActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_cbMesesActionPerformed

    private void cbIdsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbIdsItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbIdsItemStateChanged

    private void llenaIds(Object[][] datos) {
        for (int i = 0; i < datos.length; i++) {
            for (int j = 0; j < datos[i].length; j++) {
                cbIds.addItem(datos[i][j].toString());
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HistorialVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HistorialVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HistorialVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HistorialVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                HistorialVenta dialog = new HistorialVenta(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FrameDrag;
    private javax.swing.JComboBox<String> cbAños;
    private javax.swing.JComboBox<String> cbIds;
    private javax.swing.JComboBox<String> cbMeses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel pnTicketsGrid;
    // End of variables declaration//GEN-END:variables
}
