package trabajo.entornos;

import java.awt.Color;
import java.awt.Image;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {

        initComponents();

        MySQL.conecta("pepe", "pepa");
        System.out.println("inicia este");

        //MySQL.ejecutaConsulta("select idProducto as Codigo,nombre,cantidad"
        //     + "ppu,categoria  from producto;");
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                MySQL.cierra();
                System.exit(0);
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btCatalogo = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btStock = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btCatalogo.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btCatalogo.setForeground(new java.awt.Color(255, 255, 255));
        btCatalogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/catalogo.png"))); // NOI18N
        btCatalogo.setText("Catálogo");
        btCatalogo.setToolTipText("Abrir Catálogo");
        btCatalogo.setBorderPainted(false);
        btCatalogo.setContentAreaFilled(false);
        btCatalogo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btCatalogo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btCatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCatalogoActionPerformed(evt);
            }
        });
        jPanel1.add(btCatalogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 88, 260, 220));

        jButton2.setText("jButton1");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 358, 135, 76));

        btStock.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btStock.setForeground(new java.awt.Color(255, 255, 255));
        btStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/stock.png"))); // NOI18N
        btStock.setText("Stock");
        btStock.setToolTipText("Manejar Stock");
        btStock.setBorderPainted(false);
        btStock.setContentAreaFilled(false);
        btStock.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btStock.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btStockActionPerformed(evt);
            }
        });
        jPanel1.add(btStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 71, 205, -1));

        jButton3.setText("jButton1");
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, 160, 80));

        jSeparator1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 306, 23));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCatalogoActionPerformed
        // TODO add your handling code here:
        new Catalogo();
    }//GEN-LAST:event_btCatalogoActionPerformed

    private void btStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btStockActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCatalogo;
    private javax.swing.JButton btStock;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
