/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabajo.entornos;

import java.awt.Color;
import static java.awt.Frame.ICONIFIED;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeParseException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author prg
 */
public class ManejarStock extends javax.swing.JDialog {

    private int xMouse;
    private int yMouse;
    Object[][] datos;
    private Object[][] datosCat;
    private Object[][] datosPantalla;

    /**
     * Creates new form ManejarStock
     */
    public ManejarStock(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        MySQL.conecta("pepe", "pepa");
        datos = MySQL.getDatos("select idProducto from Producto order by idProducto;");
        MySQL.cierraRs();

        MySQL.conecta("pepe", "pepa");
        datosCat = MySQL.getDatos("select nombre from Categoria;");
        MySQL.cierraRs();

        initComponents();

        int ultimoId = Integer.parseInt(datos[datos.length - 1][0].toString()) + 1;
        lbUltimoID.setText(String.valueOf(ultimoId));

        for (int i = 0; i < datos.length; i++) {

            for (int j = 0; j < datos[i].length; j++) {
                cbIds.addItem(datos[i][j].toString());
            }
        }
        cbNuevoCategoria.removeAllItems();
        for (int i = 0; i < datosCat.length; i++) {
            for (int j = 0; j < datosCat[i].length; j++) {
                cbNuevoCategoria.addItem(datosCat[i][j].toString());
            }
        }

//        
//        for (int i = 0; i < datosCat.length; i++) {
//
//            for (int j = 0; j < datosCat[i].length; j++) {
//                System.out.println(datosCat[i][j].toString());
//            }
//        }
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        pnTabs = new javax.swing.JTabbedPane();
        pnExistente = new javax.swing.JPanel();
        cbIds = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbCantidad = new javax.swing.JLabel();
        lbPP1 = new javax.swing.JLabel();
        lbPVP = new javax.swing.JLabel();
        lbCategoria = new javax.swing.JLabel();
        cbCategoria = new javax.swing.JComboBox<>();
        tfPVP = new javax.swing.JTextField();
        tfPP = new javax.swing.JTextField();
        tfCantidad = new javax.swing.JTextField();
        tfNombre = new javax.swing.JTextField();
        lbPP3 = new javax.swing.JLabel();
        btActualiza = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        pnNuevo = new javax.swing.JPanel();
        lbUltimoID = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbCantidad1 = new javax.swing.JLabel();
        lbPP4 = new javax.swing.JLabel();
        lbPVP1 = new javax.swing.JLabel();
        lbPP5 = new javax.swing.JLabel();
        cbNuevoCategoria = new javax.swing.JComboBox<>();
        tfNuevoPPU = new javax.swing.JTextField();
        tfNuevoPP = new javax.swing.JTextField();
        tfNuevaCantidad = new javax.swing.JTextField();
        tfNuevoNombre = new javax.swing.JTextField();
        lbPP6 = new javax.swing.JLabel();
        btRegistra = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        FrameDrag = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(250, 213, 92));

        pnTabs.setBackground(new java.awt.Color(102, 102, 102));
        pnTabs.setAutoscrolls(true);
        pnTabs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnTabsMouseClicked(evt);
            }
        });

        pnExistente.setBackground(new java.awt.Color(102, 102, 102));

        cbIds.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        cbIds.setForeground(new java.awt.Color(204, 204, 204));
        cbIds.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbIdsItemStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(238, 238, 238));
        jLabel1.setText("ID del Producto");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(238, 238, 238));
        jLabel4.setText("Nombre");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lbCantidad.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lbCantidad.setForeground(new java.awt.Color(238, 238, 238));
        lbCantidad.setText("Cantidad");
        lbCantidad.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lbPP1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lbPP1.setForeground(new java.awt.Color(238, 238, 238));
        lbPP1.setText("Precio Proveedor");
        lbPP1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lbPVP.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lbPVP.setForeground(new java.awt.Color(238, 238, 238));
        lbPVP.setText("P.V.P");
        lbPVP.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lbCategoria.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lbCategoria.setForeground(new java.awt.Color(238, 238, 238));
        lbCategoria.setText("Categoría");
        lbCategoria.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        cbCategoria.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        cbCategoria.setForeground(new java.awt.Color(204, 204, 204));

        tfPVP.setBackground(new java.awt.Color(102, 102, 102));
        tfPVP.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        tfPVP.setForeground(new java.awt.Color(204, 204, 204));
        tfPVP.setText("...");
        tfPVP.setBorder(null);
        tfPVP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPVPActionPerformed(evt);
            }
        });

        tfPP.setBackground(new java.awt.Color(102, 102, 102));
        tfPP.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        tfPP.setForeground(new java.awt.Color(204, 204, 204));
        tfPP.setText("...");
        tfPP.setBorder(null);

        tfCantidad.setBackground(new java.awt.Color(102, 102, 102));
        tfCantidad.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        tfCantidad.setForeground(new java.awt.Color(204, 204, 204));
        tfCantidad.setText("...");
        tfCantidad.setBorder(null);

        tfNombre.setBackground(new java.awt.Color(102, 102, 102));
        tfNombre.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        tfNombre.setForeground(new java.awt.Color(238, 238, 238));
        tfNombre.setText("...");
        tfNombre.setBorder(null);
        tfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNombreActionPerformed(evt);
            }
        });

        lbPP3.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        lbPP3.setForeground(new java.awt.Color(238, 238, 238));
        lbPP3.setText("Actualizar");
        lbPP3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        btActualiza.setForeground(new java.awt.Color(204, 204, 204));
        btActualiza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/actualiza.png"))); // NOI18N
        btActualiza.setToolTipText("Click para actualizar datos del producto");
        btActualiza.setBorder(null);
        btActualiza.setBorderPainted(false);
        btActualiza.setContentAreaFilled(false);
        btActualiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btActualizaActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(102, 102, 102));

        jSeparator2.setBackground(new java.awt.Color(102, 102, 102));

        jSeparator5.setBackground(new java.awt.Color(153, 153, 153));

        jSeparator6.setBackground(new java.awt.Color(153, 153, 153));

        jSeparator7.setBackground(new java.awt.Color(153, 153, 153));

        jSeparator8.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout pnExistenteLayout = new javax.swing.GroupLayout(pnExistente);
        pnExistente.setLayout(pnExistenteLayout);
        pnExistenteLayout.setHorizontalGroup(
            pnExistenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnExistenteLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(pnExistenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnExistenteLayout.createSequentialGroup()
                        .addGroup(pnExistenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnExistenteLayout.createSequentialGroup()
                                .addComponent(lbPVP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(60, 60, 60))
                            .addGroup(pnExistenteLayout.createSequentialGroup()
                                .addGroup(pnExistenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnExistenteLayout.createSequentialGroup()
                                        .addGap(100, 100, 100)
                                        .addComponent(lbPP3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)))
                        .addGroup(pnExistenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfPP, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbIds, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfPVP, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnExistenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tfCantidad, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnExistenteLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(btActualiza))
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14))
                    .addGroup(pnExistenteLayout.createSequentialGroup()
                        .addComponent(lbPP1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(471, 471, 471))))
            .addGroup(pnExistenteLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(pnExistenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnExistenteLayout.setVerticalGroup(
            pnExistenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnExistenteLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnExistenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbIds, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(pnExistenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnExistenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnExistenteLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(tfCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(pnExistenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPP1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPP, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnExistenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPVP, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPVP, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(pnExistenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnExistenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnExistenteLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btActualiza))
                    .addGroup(pnExistenteLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(lbPP3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pnTabs.addTab("Existente", pnExistente);

        pnNuevo.setBackground(new java.awt.Color(102, 102, 102));

        lbUltimoID.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lbUltimoID.setForeground(new java.awt.Color(238, 238, 238));
        lbUltimoID.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(238, 238, 238));
        jLabel5.setText("Nombre");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lbCantidad1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lbCantidad1.setForeground(new java.awt.Color(238, 238, 238));
        lbCantidad1.setText("Cantidad");
        lbCantidad1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lbPP4.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lbPP4.setForeground(new java.awt.Color(238, 238, 238));
        lbPP4.setText("Precio Proveedor");
        lbPP4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lbPVP1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lbPVP1.setForeground(new java.awt.Color(238, 238, 238));
        lbPVP1.setText("P.V.P");
        lbPVP1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lbPP5.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lbPP5.setForeground(new java.awt.Color(238, 238, 238));
        lbPP5.setText("Categoría");
        lbPP5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        cbNuevoCategoria.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        cbNuevoCategoria.setForeground(new java.awt.Color(204, 204, 204));

        tfNuevoPPU.setBackground(new java.awt.Color(102, 102, 102));
        tfNuevoPPU.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        tfNuevoPPU.setForeground(new java.awt.Color(204, 204, 204));
        tfNuevoPPU.setText("...");
        tfNuevoPPU.setBorder(null);
        tfNuevoPPU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNuevoPPUActionPerformed(evt);
            }
        });

        tfNuevoPP.setBackground(new java.awt.Color(102, 102, 102));
        tfNuevoPP.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        tfNuevoPP.setForeground(new java.awt.Color(204, 204, 204));
        tfNuevoPP.setText("...");
        tfNuevoPP.setBorder(null);

        tfNuevaCantidad.setBackground(new java.awt.Color(102, 102, 102));
        tfNuevaCantidad.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        tfNuevaCantidad.setForeground(new java.awt.Color(204, 204, 204));
        tfNuevaCantidad.setText("...");
        tfNuevaCantidad.setBorder(null);

        tfNuevoNombre.setBackground(new java.awt.Color(102, 102, 102));
        tfNuevoNombre.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        tfNuevoNombre.setForeground(new java.awt.Color(238, 238, 238));
        tfNuevoNombre.setText("...");
        tfNuevoNombre.setBorder(null);
        tfNuevoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNuevoNombreActionPerformed(evt);
            }
        });

        lbPP6.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        lbPP6.setForeground(new java.awt.Color(238, 238, 238));
        lbPP6.setText("Registrar");
        lbPP6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        btRegistra.setForeground(new java.awt.Color(204, 204, 204));
        btRegistra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/registrar.png"))); // NOI18N
        btRegistra.setToolTipText("Click para registrar producto");
        btRegistra.setBorder(null);
        btRegistra.setBorderPainted(false);
        btRegistra.setContentAreaFilled(false);
        btRegistra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegistraActionPerformed(evt);
            }
        });

        jSeparator3.setBackground(new java.awt.Color(102, 102, 102));

        jSeparator4.setBackground(new java.awt.Color(102, 102, 102));

        jSeparator9.setBackground(new java.awt.Color(153, 153, 153));

        jSeparator10.setBackground(new java.awt.Color(153, 153, 153));

        jSeparator11.setBackground(new java.awt.Color(153, 153, 153));

        jSeparator12.setBackground(new java.awt.Color(153, 153, 153));

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(238, 238, 238));
        jLabel6.setText("ID del Producto");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout pnNuevoLayout = new javax.swing.GroupLayout(pnNuevo);
        pnNuevo.setLayout(pnNuevoLayout);
        pnNuevoLayout.setHorizontalGroup(
            pnNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNuevoLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(pnNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnNuevoLayout.createSequentialGroup()
                        .addGroup(pnNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnNuevoLayout.createSequentialGroup()
                                .addComponent(lbPVP1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(60, 60, 60))
                            .addGroup(pnNuevoLayout.createSequentialGroup()
                                .addGroup(pnNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbCantidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbPP5, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnNuevoLayout.createSequentialGroup()
                                        .addGap(100, 100, 100)
                                        .addComponent(lbPP6, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)))
                        .addGroup(pnNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNuevoPP, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbNuevoCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNuevoPPU, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tfNuevaCantidad, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfNuevoNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnNuevoLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(btRegistra))
                            .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbUltimoID, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14))
                    .addGroup(pnNuevoLayout.createSequentialGroup()
                        .addComponent(lbPP4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(471, 471, 471))))
            .addGroup(pnNuevoLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(pnNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnNuevoLayout.setVerticalGroup(
            pnNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnNuevoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbUltimoID, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(pnNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNuevoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbCantidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnNuevoLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(tfNuevaCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(pnNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPP4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNuevoPP, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNuevoPPU, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPVP1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(pnNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbNuevoCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPP5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnNuevoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btRegistra))
                    .addGroup(pnNuevoLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(lbPP6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnTabs.addTab("Nuevo", pnNuevo);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(54, 65, 137));
        jLabel3.setText("x");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        FrameDrag.setBackground(new java.awt.Color(204, 204, 204));
        FrameDrag.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        FrameDrag.setForeground(new java.awt.Color(54, 65, 137));
        FrameDrag.setText("Manejar Stock Almacén");
        FrameDrag.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                FrameDragMouseDragged(evt);
            }
        });
        FrameDrag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FrameDragMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnTabs)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(FrameDrag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FrameDrag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3))
                .addGap(2, 2, 2)
                .addComponent(pnTabs, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNombreActionPerformed

    private void tfPVPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPVPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPVPActionPerformed

    private void FrameDragMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FrameDragMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_FrameDragMouseDragged

    private void FrameDragMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FrameDragMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_FrameDragMousePressed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void cbIdsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbIdsItemStateChanged
        // TODO add your handling code here:
        datosPantalla = MySQL.getDatos("select nombre,cantidad,pp,ppu,categoria from producto where idProducto =" + cbIds.getSelectedItem().toString() + ";");
        MySQL.cierraRs();

//        for (int i = 0; i < datosPantalla.length; i++) {
//            for (int j = 0; j < datosPantalla[i].length; j++) {
//                System.out.println(datosPantalla[i][j].toString());
//            }
//        }
        tfNombre.setText(datosPantalla[0][0].toString());
        tfCantidad.setText(datosPantalla[0][1].toString());
        tfPP.setText(datosPantalla[0][2].toString());
        tfPVP.setText(datosPantalla[0][3].toString());
        //Combo Categorías
        cbCategoria.removeAllItems();
        for (int i = 0; i < datosCat.length; i++) {
            for (int j = 0; j < datosCat[i].length; j++) {
                cbCategoria.addItem(datosCat[i][j].toString());
            }
        }

        for (int i = 0; i < cbCategoria.getItemCount(); i++) {
            if (cbCategoria.getItemAt(i).compareToIgnoreCase(datosPantalla[0][4].toString()) == 0) {
                cbCategoria.setSelectedIndex(i);
                break;
            }

        }

    }//GEN-LAST:event_cbIdsItemStateChanged

    private void btActualizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btActualizaActionPerformed
        // TODO add your handling code here:
        Object[] datosInsertar = new Object[6];
        boolean datosCorrectos = true;

        if (tfNombre.getText().isEmpty()) {
            tfNombre.setBackground(Color.red);
            datosCorrectos = false;
        } else {
            tfNombre.setBackground(new java.awt.Color(102, 102, 102));
        }

        try {
            Integer.parseInt(tfCantidad.getText());
            tfCantidad.setBackground(new java.awt.Color(102, 102, 102));
        } catch (NumberFormatException eParse) {
            datosCorrectos = false;
            tfCantidad.setBackground(Color.red);
        }

        try {
            Double.parseDouble(tfPP.getText());
            tfPP.setBackground(new java.awt.Color(102, 102, 102));
        } catch (NumberFormatException eParse) {
            datosCorrectos = false;
            tfPP.setBackground(Color.red);

        }

        try {
            Double.parseDouble(tfPVP.getText());
            tfPVP.setBackground(new java.awt.Color(102, 102, 102));
        } catch (NumberFormatException eParse) {
            datosCorrectos = false;
            tfPVP.setBackground(Color.red);

        }

        if (datosCorrectos) {

            datosInsertar[0] = cbIds.getSelectedItem().toString();
            datosInsertar[1] = tfNombre.getText();
            datosInsertar[2] = tfCantidad.getText();
            datosInsertar[3] = tfPP.getText();
            datosInsertar[4] = tfPVP.getText();
            datosInsertar[5] = cbCategoria.getSelectedItem().toString();

            Object[][] datosComparar = MySQL.getDatos("select * from producto where idProducto = " + datosInsertar[0] + ";");
            MySQL.cierraRs();

            if (datosInsertar[1].toString().compareToIgnoreCase(datosComparar[0][1].toString()) != 0) {
                System.out.println("Nombre diferente");
                int afectadas = MySQL.ejecutaConsultaAccion("update producto set nombre ='" + datosInsertar[1] + "' where idProducto =" + datosInsertar[0] + ";");
                System.out.println("Nombre filas afectadas: " + afectadas);
            }

            if (datosInsertar[2].toString().compareToIgnoreCase(datosComparar[0][2].toString()) != 0) {
                System.out.println("Cantidad diferente");

                int afectadas = MySQL.ejecutaConsultaAccion("update producto set cantidad =" + datosInsertar[2] + " where idProducto =" + datosInsertar[0] + ";");
                System.out.println("Cantidad filas afectadas: " + afectadas);
            }

            if (datosInsertar[3].toString().compareToIgnoreCase(datosComparar[0][3].toString()) != 0) {
                System.out.println("PP diferente");
                int afectadas = MySQL.ejecutaConsultaAccion("update producto set pp =" + datosInsertar[3] + " where idProducto =" + datosInsertar[0] + ";");
                System.out.println("PP filas afectadas: " + afectadas);
            }

            if (datosInsertar[4].toString().compareToIgnoreCase(datosComparar[0][4].toString()) != 0) {
                System.out.println("PVP diferente");
                int afectadas = MySQL.ejecutaConsultaAccion("update producto set ppu = " + datosInsertar[4] + " where idProducto =" + datosInsertar[0] + ";");
                System.out.println("PVP(ppu) filas afectadas: " + afectadas);
            }

            if (datosInsertar[5].toString().compareToIgnoreCase(datosComparar[0][5].toString()) != 0) {
                System.out.println("Categoria diferente");
                int afectadas = MySQL.ejecutaConsultaAccion("update producto set categoria = '" + datosInsertar[5] + "' where idProducto =" + datosInsertar[0] + ";");
                System.out.println("Nombre filas afectadas: " + afectadas);
            }

            if (Integer.parseInt(datosComparar[0][2].toString()) != Integer.parseInt(datosInsertar[2].toString())) {
                int diferencia = Integer.parseInt(datosInsertar[2].toString()) - Integer.parseInt(datosComparar[0][2].toString());
                double dineroDiferencia = diferencia * Double.parseDouble(datosInsertar[3].toString());//diferencia*pp
                double ultimaCantidad = Double.parseDouble(MySQL.getUltimoDatoIndividual("select * from fondo;").toString());
                MySQL.cierraRs();
                double ultimaCantidadActualizada = ultimaCantidad - dineroDiferencia;
                MySQL.ejecutaConsultaAccion("insert into fondo values (" + ultimaCantidadActualizada + ");");

            }
            System.out.println("todo ok");
        }


    }//GEN-LAST:event_btActualizaActionPerformed

    private void tfNuevoPPUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNuevoPPUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNuevoPPUActionPerformed

    private void tfNuevoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNuevoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNuevoNombreActionPerformed

    private void btRegistraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegistraActionPerformed
        // TODO add your handling code here:
        System.out.println("has pulsado registrar");

        Object[] nuevoProd = new Object[6];
        boolean datosCorrectos = true;

        if (tfNuevoNombre.getText().isEmpty()) {
            tfNuevoNombre.setBackground(Color.red);
            datosCorrectos = false;
        } else {
            tfNuevoNombre.setBackground(new java.awt.Color(102, 102, 102));
        }
        if (tfNuevoNombre.getText().compareToIgnoreCase("...") == 0) {
            tfNuevoNombre.setBackground(Color.red);
            datosCorrectos = false;
        } else {
            tfNuevoNombre.setBackground(new java.awt.Color(102, 102, 102));
        }

        try {
            Integer.parseInt(tfNuevaCantidad.getText());
            tfNuevaCantidad.setBackground(new java.awt.Color(102, 102, 102));
        } catch (NumberFormatException eParse) {
            datosCorrectos = false;
            tfNuevaCantidad.setBackground(Color.red);
        }

        try {
            Double.parseDouble(tfNuevoPP.getText());
            tfNuevoPP.setBackground(new java.awt.Color(102, 102, 102));
        } catch (NumberFormatException eParse) {
            datosCorrectos = false;
            tfNuevoPP.setBackground(Color.red);

        }

        try {
            Double.parseDouble(tfNuevoPPU.getText());
            tfNuevoPPU.setBackground(new java.awt.Color(102, 102, 102));
        } catch (NumberFormatException eParse) {
            datosCorrectos = false;
            tfNuevoPPU.setBackground(Color.red);

        }

        if (datosCorrectos) {

            nuevoProd[0] = lbUltimoID.getText();
            nuevoProd[1] = tfNuevoNombre.getText();
            nuevoProd[2] = tfNuevaCantidad.getText();
            nuevoProd[3] = tfNuevoPP.getText();
            nuevoProd[4] = tfNuevoPPU.getText();
            nuevoProd[5] = cbNuevoCategoria.getSelectedItem().toString();
        }

        System.out.println("insert into producto values (" + nuevoProd[0] + ","
                + "'" + nuevoProd[1] + "'," + nuevoProd[2] + "," + nuevoProd[3] + "," + nuevoProd[4] + ",'" + nuevoProd[5] + "');");
        int afectadas = MySQL.ejecutaConsultaAccion("insert into producto values (" + nuevoProd[0] + ","
                + "'" + nuevoProd[1] + "'," + nuevoProd[2] + "," + nuevoProd[3] + "," + nuevoProd[4] + ",'" + nuevoProd[5] + "');");
        System.out.println("Insercion: " + afectadas + " filas afectadas");
        if (afectadas >= 1) {

            int diferencia = Integer.parseInt(tfNuevaCantidad.getText());
            double dineroDiferencia = diferencia * Double.parseDouble(tfNuevoPP.getText());//diferencia*pp
            double ultimaCantidad = Double.parseDouble(MySQL.getUltimoDatoIndividual("select * from fondo;").toString());
            MySQL.cierraRs();
            double ultimaCantidadActualizada = ultimaCantidad - dineroDiferencia;
            MySQL.ejecutaConsultaAccion("insert into fondo values (" + ultimaCantidadActualizada + ");");

            datos = MySQL.getDatos("select idProducto from Producto order by idProducto;");
            MySQL.cierraRs();
            int ultimoId = Integer.parseInt(datos[datos.length - 1][0].toString()) + 1;
            lbUltimoID.setText(String.valueOf(ultimoId));

            tfNuevoNombre.setText("...");
            tfNuevaCantidad.setText("...");
            tfNuevoPP.setText("...");
            tfNuevoPPU.setText("...");

        }


    }//GEN-LAST:event_btRegistraActionPerformed

    private void pnTabsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnTabsMouseClicked
        // TODO add your handling code here:
        datos = MySQL.getDatos("select idProducto from Producto order by idProducto;");
        MySQL.cierraRs();
        int ultimoId = Integer.parseInt(datos[datos.length - 1][0].toString()) + 1;
        lbUltimoID.setText(String.valueOf(ultimoId));
    }//GEN-LAST:event_pnTabsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManejarStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManejarStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManejarStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManejarStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ManejarStock dialog = new ManejarStock(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FrameDrag;
    private javax.swing.JButton btActualiza;
    private javax.swing.JButton btRegistra;
    private javax.swing.JComboBox<String> cbCategoria;
    private javax.swing.JComboBox<String> cbIds;
    private javax.swing.JComboBox<String> cbNuevoCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lbCantidad;
    private javax.swing.JLabel lbCantidad1;
    private javax.swing.JLabel lbCategoria;
    private javax.swing.JLabel lbPP1;
    private javax.swing.JLabel lbPP3;
    private javax.swing.JLabel lbPP4;
    private javax.swing.JLabel lbPP5;
    private javax.swing.JLabel lbPP6;
    private javax.swing.JLabel lbPVP;
    private javax.swing.JLabel lbPVP1;
    private javax.swing.JLabel lbUltimoID;
    private javax.swing.JPanel pnExistente;
    private javax.swing.JPanel pnNuevo;
    private javax.swing.JTabbedPane pnTabs;
    private javax.swing.JTextField tfCantidad;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfNuevaCantidad;
    private javax.swing.JTextField tfNuevoNombre;
    private javax.swing.JTextField tfNuevoPP;
    private javax.swing.JTextField tfNuevoPPU;
    private javax.swing.JTextField tfPP;
    private javax.swing.JTextField tfPVP;
    // End of variables declaration//GEN-END:variables
}
